### ISSUE TITLE
Assertions in sample.py

### ISSUE THREAD

**Issue by aztensepp** [junkurihara/PySSS#1]
Hello,

I am trying out your nice library and suggest to include some assertions in the sample.py (if you'd like):

def main():
    # set params
    threshold = 5 # k
    ramp = 3 # L 
    num = 10 # n
    index_list = [1, 2, 4, 5,6]
    shares = []

    assert   ramp >1 and ramp<threshold
    assert   threshold<num
    assert   len(index_list) >= threshold

regards 
florian

**Comment by junkurihara** [comment]
Hi Florian,

Thank you for useful comments. I agree that assertions should be included in sample.py, and just updated it!

Best,
Jun
