### ISSUE TITLE
xor_sss.py hasn't been implemented yet?

### ISSUE THREAD

**Issue by MrSiz** [junkurihara/PySSS#2]
I try to implement the xor_sss with python, but i failed.

**Comment by junkurihara** [comment]
Hello @MrSiz,
correct, it is not implemented yet in PySSS. `xor_sss.py` has just stubs.

**Comment by MrSiz** [comment]
@junkurihara But in the paper <<A New (k, n)-Threshold Secret Sharing Scheme and Its Extension>>, you did the evaluation. I'm curious about the implementation of function `MAT()`.

**Comment by MrSiz** [comment]
Can you open source your implementation？Thanks in advance.

**Comment by MrSiz** [comment]
Could you open source your implementation？Thanks in advance.

**Comment by junkurihara** [comment]
Hey @MrSiz,

Unfortunately, it cannot be open-source since it has been done in a company as a commercial software. I tried to re-implement it in Python (originally C++) several years ago, but I have not been having enough time to do that. I can't promise that I would do that in near future...

**Comment by junkurihara** [comment]
The algorithm itself is open, so you can implement yourself if you like. Please refer to the full paper for the detailed algorithm.
https://junkurihara.github.io/repo/ieice-e91-a_09_2365.pdf
